export const categories = {
  antiguo: "antiguo",
  nuevo: "nuevo",
  conferencia: "conferencia",
};

const { antiguo, nuevo, conferencia } = categories;

export const questions = [
  //antiguo testamento
  {
    id: 1,
    difficulty: "Medio",
    category: antiguo,
    question: "¿De Qué tela estaba hecha la tunica sagrada del sumo sacerdote?",
    correct_answer: "Lino",
    incorrect_answers: ["Algodon", "Seda", "Purpura"],
    public: [40, 10, 20, 30],
    info: "",
    bible: "Lev 16:4",
  },
  {
    id: 2,
    difficulty: "Facil",
    category: antiguo,
    question:
      "¿Cómo se llamaba el hombre que quiso destruir a los judios en el reino de Asuero?",
    correct_answer: "Aman",
    incorrect_answers: ["Sedateres", "Jair", "Jeconias"],
    public: [45, 20, 15, 20],
    info: "Esta historia se encuentra dentro de uno de los libros historicos",
    bible: "Est 3:6",
  },
  {
    id: 3,
    difficulty: "Dificil",
    category: antiguo,
    question: "¿Cuántos capitulos tiene el libro de Daniel?",
    correct_answer: "12 capitulos",
    incorrect_answers: ["14 capitulos", "10 capitulos", "8 capitulos"],
    public: [30, 40, 20, 10],
    info: "",
    bible: "Dan 1-12",
  },
  {
    id: 4,
    difficulty: "Facil",
    category: antiguo,
    question: "Qué mujer fue jueza y líder de Israel según dice la Biblia?",
    correct_answer: "Debora",
    incorrect_answers: ["Jael", "Ester", "Rut"],
    public: [30, 40, 20, 10],
    info: "",
    bible: "Ju 4:4-5",
  },
  {
    id: 5,
    difficulty: "Dificil",
    category: antiguo,
    question: "¿Quién reinaba en Judá cuando Nabucodonosor sitió Jerusalén?",
    correct_answer: "Joacim",
    incorrect_answers: ["Acaz", "Davin", "Saul"],
    public: [50, 40, 20, 10],
    info: "",
    bible: "Dan 1:1",
  },
  {
    id: 6,
    difficulty: "Dificil",
    category: antiguo,
    question:
      "¿Cómo se llamaba el rey de Israel que sacrificó en el fuego a su hijo?",
    correct_answer: "Acaz",
    incorrect_answers: ["Joacaz", "Joaz", "Joacin"],
    public: [50, 40, 20, 10],
    info: "",
    bible: "Rey 16:3-4",
  },
  {
    id: 7,
    difficulty: "Medio",
    category: antiguo,
    question: "¿Cuál era el nombre de la única hija de Lea?",
    correct_answer: "Dina",
    incorrect_answers: ["Raquel", "Zilpa", "Jael"],
    public: [50, 40, 20, 10],
    info: "",
    bible: "Gén 30:21",
  },
  {
    id: 8,
    difficulty: "Medio",
    category: antiguo,
    question: "¿A cuál tribu pertenecía Saúl?",
    correct_answer: "Benjamin",
    incorrect_answers: ["Neftali", "Levi", "Juda"],
    public: [50, 40, 20, 10],
    info: "",
    bible: "Gén 30:21",
  },
  {
    id: 9,
    difficulty: "Dificil",
    category: antiguo,
    question: "¿Cuál era el nombre babilónico de Daniel?",
    correct_answer: "Beltsasar",
    incorrect_answers: ["Azarías", "Abednego", "Misael"],
    public: [50, 40, 20, 10],
    info: "",
    bible: "Dan 1:7.",
  },
  {
    id: 10,
    difficulty: "Dificil",
    category: antiguo,
    question: "¿Cuál es el versículo más largo de la Biblia?",
    correct_answer: "Ester 8:9",
    incorrect_answers: [
      "Salmos 119:43",
      "Isaías 24:2",
      "Ninguno de los anteriores",
    ],
    public: [50, 40, 20, 10],
    info: "",
    bible: "Ester",
  },
  {
    id: 11,
    difficulty: "Muy Dificil",
    category: antiguo,
    question:
      "¿Qué libros de la Biblia terminan con un signo de interrogación?",
    correct_answer: "Jonas, Nahum",
    incorrect_answers: ["Joel, Nahum", "Judas, Pedro", "Apocalipsis, Ester"],
    public: [50, 40, 20, 10],
    info: "",
    bible: "Jonás 4:11, Nahum 3:19",
  },
  {
    id: 12,
    difficulty: "Dificil",
    category: antiguo,
    question: "¿Cuántos años más vivió Noé después del diluvio?",
    correct_answer: "350 años",
    incorrect_answers: ["100 años", "7 días", "250 años"],
    public: [50, 40, 20, 10],
    info: "",
    bible: "Gén 9:28-29",
  },
  {
    id: 13,
    difficulty: "Dificil",
    category: antiguo,
    question: "¿Cuál de estos libros tiene más de un capítulo?",
    correct_answer: "Joel",
    incorrect_answers: ["Abdías", "Judas", "todos tienen un capitulo"],
    public: [50, 40, 20, 10],
    info: "",
    bible: "Joel",
  },
  {
    id: 14,
    difficulty: "Dificil",
    category: antiguo,
    question: "¿Quién fue el rey y profeta de salem en el tiempo de Abraham?",
    correct_answer: "Melquisedec",
    incorrect_answers: ["Joacaz", "Manasés", "Zacarias"],
    public: [50, 40, 20, 10],
    info: "",
    bible: "Gén 14:18",
  },
  {
    id: 15,
    difficulty: "Dificil",
    category: antiguo,
    question: "¿Cuántos carros de hierro tenía Jabín?",
    correct_answer: "900",
    incorrect_answers: ["300", "100", "no esta en la biblia"],
    public: [50, 40, 20, 10],
    info: "",
    bible: "Jue 4:2,13",
  },
  {
    id: 16,
    difficulty: "Medio",
    category: antiguo,
    question:
      "¿Durante cuál día de la creación creó Dios el sol, la luna y las estrellas?",
    correct_answer: "4º día",
    incorrect_answers: ["1º día", "3º día", "6º día"],
    public: [50, 40, 20, 10],
    info: "",
    bible: "Hag",
  },
  {
    id: 17,
    difficulty: "Facil",
    category: antiguo,
    question: "¿Qué créo Dios el primer día?",
    correct_answer: "Los cielos y la tierra",
    incorrect_answers: ["Las lumbreras", "Las expansiones", "Seres vivientes"],
    public: [20, 60, 15, 5],
    info: "",
    bible: "Gén",
  },
  {
    id: 18,
    difficulty: "Dificil",
    category: antiguo,
    question: "¿Cómo se llamaba el padre del profeta Samuel?",
    correct_answer: "Elcana",
    incorrect_answers: ["Manoa", "Abiel", "Ofni"],
    public: [50, 40, 20, 10],
    info: "",
    bible: "1 Sam 1:1",
  },
  {
    id: 19,
    difficulty: "Dificil",
    category: antiguo,
    question:
      "¿Cuánto tiempo estuvo el pueblo de Israel en Egipto antes de ser libertados?",
    correct_answer: "430",
    incorrect_answers: ["470", "450", "410"],
    public: [50, 40, 20, 10],
    info: "",
    bible: "Ex 12:40",
  },
  {
    id: 20,
    difficulty: "Muy Dificil",
    category: antiguo,
    question:
      "¿La madera de qué árbol utilizó Solomón para construir el templo?",
    correct_answer: "Cedro",
    incorrect_answers: ["Gofer", "Almendro", "Ciprés"],
    public: [50, 40, 20, 10],
    info: "",
    bible: "1 Rey 5:6",
  },
  {
    id: 21,
    difficulty: "Dificil",
    category: antiguo,
    question: "¿Quién fue el último juez de todo Israel?",
    correct_answer: "Samuel",
    incorrect_answers: ["Sansón", "Jefté", "Gedeón"],
    public: [50, 40, 20, 10],
    info: "",
    bible: "1 Sam 7:15",
  },
  {
    id: 22,
    difficulty: "Muy Dificil",
    category: antiguo,
    question: "¿Cuántos hijos tuvo en total el profeta Oseas?",
    correct_answer: "3 Hijos",
    incorrect_answers: ["5 Hijos", "4 Hijos", "2 Hijos"],
    public: [50, 40, 20, 10],
    info: "",
    bible: "Os 1:3-8",
  },
  {
    id: 23,
    difficulty: "Medio",
    category: antiguo,
    question:
      "¿La madera de qué árbol utilizó Solomón para construir el templo?",
    correct_answer: "Cedro",
    incorrect_answers: ["Gofer", "Almendro", "Ciprés"],
    public: [50, 40, 20, 10],
    info: "",
    bible: "1 Rey 5:6",
  },
  {
    id: 24,
    difficulty: "Dificil",
    category: antiguo,
    question:
      "¿Qué rey de Judá mostró toda la riqueza del reino a los mensajeros de Babilonia?",
    correct_answer: "Ezequías",
    incorrect_answers: ["Manasés", "Acaz", "Roboam"],
    public: [50, 40, 20, 10],
    info: "",
    bible: "1 Rey 20:13",
  },
  //nuevo testamento

  {
    id: 100,
    difficulty: "Medio",
    category: nuevo,
    question: "En que evangelios se describe la genealogia de Jesus?",
    correct_answer: "Mateo y Lucas",
    incorrect_answers: ["Mateo y Juan", "Juan y Lucas", "Lucas y Juan"],
    public: [40, 10, 20, 30],
    info: "",
    bible: "Mt.1:1-7; Lc.3:23-38",
  },

  {
    id: 101,
    difficulty: "Dificil",
    category: nuevo,
    question: "¿A quién llamó el Apóstol Pablo 'el médico amado'?",
    correct_answer: "Lucas",
    incorrect_answers: ["Demas", "Jesus", "Pedro"],
    public: [50, 40, 20, 10],
    info: "",
    bible: "Col 4:14.",
  },
  {
    id: 102,
    difficulty: "Muy Dificil",
    category: nuevo,
    question:
      "¿Qué grupo religioso de los tiempos de Jesús enseñaba que no hay resurrección?",
    correct_answer: "Saduceos",
    incorrect_answers: ["Fariseos", "Nazarenos", "Zelotes"],
    public: [50, 40, 20, 10],
    info: "",
    bible: "Mt 22:23",
  },
  {
    id: 103,
    difficulty: "Dificil",
    category: nuevo,
    question: "¿Las llaves de qué reino prometio darle Jesús a Pedro?",
    correct_answer: "De los Cielos",
    incorrect_answers: ["Del Hades", "De la Tierra", "De la Iglesia"],
    public: [50, 40, 20, 10],
    info: "",
    bible: "Mt 16:19",
  },
  {
    id: 104,
    difficulty: "Muy Dificil",
    category: nuevo,
    question:
      "¿Cuántas veces Pablo rogó a Dios que le quitase el aguijón de su carne?",
    correct_answer: "3 veces",
    incorrect_answers: ["5 veces", "4 veces", "2 veces"],
    public: [50, 40, 20, 10],
    info: "",
    bible: "2 Cor 12:8",
  },
  {
    id: 200,
    difficulty: "Medio",
    category: conferencia,
    question:
      "¿Quién perdió la vida por haber mentido al Espíritu Santo al retener parte de una ofrenda?",
    correct_answer: "Ananías",
    incorrect_answers: ["Judas Iscariote", "Caín", "Uza"],
    public: [65, 20, 10, 5],
    info: "",
    bible: "Hechos 5:1-10",
  },
  {
    id: 201,
    difficulty: "Medio",
    category: conferencia,
    question: "¿Quién se quitó la vida después de traicionar a Jesús?",
    correct_answer: "Judas",
    incorrect_answers: ["Pedro", "Caín", "Herodes"],
    public: [5, 85, 5, 5],
    info: "",
    bible: "Mateo 27:3-5",
  },
  {
    id: 202,
    difficulty: "Medio",
    category: conferencia,
    question: "¿Quién murió al tocar el arca del pacto sin autorización?",
    correct_answer: "Uza",
    incorrect_answers: ["Joacaz", "Abiu", "Nadab"],
    public: [10, 70, 10, 10],
    info: "",
    bible: "2 Samuel 6:6-7",
  },
  {
    id: 203,
    difficulty: "Medio",
    category: conferencia,
    question: "¿Qué rey murió trágicamente después de consultar a una adivina?",
    correct_answer: "Saúl",
    incorrect_answers: ["David", "Salomón", "Ezequías"],
    public: [80, 5, 10, 5],
    info: "",
    bible: "1 Samuel 28 y 31",
  },
  {
    id: 204,
    difficulty: "Medio",
    category: conferencia,
    question:
      "¿Qué personajes murieron por ofrecer fuego extraño delante de Dios?",
    correct_answer: "Nadab y Abiú",
    incorrect_answers: [
      "Elí y sus hijos",
      "Moisés y Aarón",
      "Coré y sus seguidores",
    ],
    public: [10, 5, 70, 15],
    info: "",
    bible: "Levítico 10:1-2",
  },
  {
    id: 205,
    difficulty: "Facil",
    category: conferencia,
    question: "¿Quién fue tragado por un gran pez al desobedecer a Dios?",
    correct_answer: "Jonás",
    incorrect_answers: ["Elías", "Moisés", "Noé"],
    public: [65, 10, 15, 10],
    info: "",
    bible: "Jonás 1:17",
  },
  {
    id: 206,
    difficulty: "Facil",
    category: conferencia,
    question: "¿Qué mujer fue convertida en estatua de sal?",
    correct_answer: "La esposa de Lot",
    incorrect_answers: ["Sara", "Miriam", "Débora"],
    public: [55, 20, 15, 10],
    info: "",
    bible: "Génesis 19:26",
  },
  {
    id: 207,
    difficulty: "Facil",
    category: conferencia,
    question: "¿Quién fue lanzado al foso de los leones?",
    correct_answer: "Daniel",
    incorrect_answers: ["Samuel", "David", "Isaías"],
    public: [80, 5, 10, 5],
    info: "",
    bible: "Daniel 6:16",
  },
  {
    id: 208,
    difficulty: "Medio",
    category: conferencia,
    question: "¿Qué ciudad fue destruida junto con Gomorra?",
    correct_answer: "Sodoma",
    incorrect_answers: ["Jericó", "Nínive", "Betel"],
    public: [75, 5, 10, 10],
    info: "",
    bible: "Génesis 19:24",
  },
  {
    id: 209,
    difficulty: "Facil",
    category: conferencia,
    question: "¿Quién construyó el arca para salvar a su familia?",
    correct_answer: "Noé",
    incorrect_answers: ["Abraham", "Moisés", "Jacob"],
    public: [90, 3, 5, 2],
    info: "",
    bible: "Génesis 6:13-14",
  },
  {
    id: 210,
    difficulty: "Dificil",
    category: conferencia,
    question:
      "¿Qué personaje bíblico fue reprendido por desperdiciar su única oportunidad de redención al vender su primogenitura?",
    correct_answer: "Esaú",
    incorrect_answers: ["Caín", "Saúl", "Acab"],
    public: [20, 10, 40, 30],
    info: "",
    bible: "Génesis 25:29-34",
  },
  {
    id: 211,
    difficulty: "Muy Dificil",
    category: conferencia,
    question:
      "¿Qué rey bíblico se desesperó y se quitó la vida tras ver perdida su única esperanza en la batalla?",
    correct_answer: "Saúl",
    incorrect_answers: ["Jeroboam", "Manasés", "Roboam"],
    public: [35, 15, 30, 20],
    info: "",
    bible: "1 Samuel 31:3-5",
  },
  {
    id: 212,
    difficulty: "Muy Dificil",
    category: conferencia,
    question:
      "¿Quién perdió su única oportunidad de salvación por no entrar al arca de Noé?",
    correct_answer: "La generación antediluviana",
    incorrect_answers: ["Lot", "Los egipcios", "Los amorreos"],
    public: [50, 15, 20, 15],
    info: "",
    bible: "Génesis 7:21-23",
  },
  {
    id: 213,
    difficulty: "Dificil",
    category: conferencia,
    question:
      "¿Qué discípulo casi muere por su descuido al quedarse dormido durante una enseñanza?",
    correct_answer: "Eutico",
    incorrect_answers: ["Tito", "Timoteo", "Esteban"],
    public: [20, 20, 30, 30],
    info: "",
    bible: "Hechos 20:9",
  },
  {
    id: 214,
    difficulty: "Dificil",
    category: conferencia,
    question:
      "¿Quién fue consumido repentinamente por mentir al Espíritu Santo y no tuvo una segunda oportunidad?",
    correct_answer: "Ananías y Safira",
    incorrect_answers: [
      "Simón el Mago",
      "Elí y sus hijos",
      "Saúl y su escudero",
    ],
    public: [60, 10, 20, 10],
    info: "",
    bible: "Hechos 5:1-10",
  },
  {
    id: 215,
    difficulty: "Dificil",
    category: conferencia,
    question:
      "¿Quién fue convertido en estatua de sal por mirar atrás, desobedeciendo la instrucción divina?",
    correct_answer: "La esposa de Lot",
    incorrect_answers: [
      "La concubina del levita",
      "Mical, hija de Saúl",
      "Tamar",
    ],
    public: [55, 15, 20, 10],
    info: "",
    bible: "Génesis 19:26",
  },
  {
    id: 216,
    difficulty: "Dificil",
    category: conferencia,
    question:
      "¿Qué rey fue herido de muerte por no dar la gloria a Dios y murió comido de gusanos?",
    correct_answer: "Herodes Agripa",
    incorrect_answers: ["Nabucodonosor", "Faraón", "Acab"],
    public: [50, 10, 30, 10],
    info: "",
    bible: "Hechos 12:21-23",
  },
  {
    id: 217,
    difficulty: "Dificil",
    category: conferencia,
    question:
      "¿Qué joven se durmió durante la predicación de Pablo, cayó del tercer piso y murió, pero fue resucitado?",
    correct_answer: "Eutico",
    incorrect_answers: ["Tíquico", "Onésimo", "Timoteo"],
    public: [45, 20, 25, 10],
    info: "",
    bible: "Hechos 20:9-10",
  },
  {
    id: 218,
    difficulty: "Dificil",
    category: conferencia,
    question:
      "¿Qué hombre fue tragado por la tierra junto con su familia y posesiones por rebelarse contra Moisés?",
    correct_answer: "Coré",
    incorrect_answers: ["Datán", "Abiram", "Balaam"],
    public: [40, 30, 20, 10],
    info: "",
    bible: "Números 16:31-33",
  },
];
